# Configuration for .github/workflows/pull_request_label.yml.

'type-infra':
  - changed-files:
    - any-glob-to-any-file: '.github/**'

'package:appengine':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/appengine/**'

'package:gcloud':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/gcloud/**'

'package:native_synchronization':
  - changed-files:
    - any-glob-to-any-file: 'pkgs/native_synchronization/**'
