include: package:lints/core.yaml

analyzer:
  errors:
    # TODO: We need to update the grpc generator to escape html entities in
    # proto comments.
    unintended_html_in_doc_comment: ignore

  exclude:
    - tmp/**
