name: appengine
version: 0.13.10
description: >-
  Support for using Dart as a custom runtime on Google App Engine Flexible
  Environment.
repository: https://github.com/dart-lang/labs/tree/main/pkgs/appengine
issue_tracker: https://github.com/dart-lang/labs/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Aappengine

topics:
  - cloud
  - gcp

environment:
  sdk: ^3.0.0

dependencies:
  fixnum: ^1.0.0
  gcloud: ^0.8.10
  googleapis_auth: ^1.1.0
  grpc: ^4.0.1
  http: '>=0.13.3 <2.0.0'
  logging: ^1.0.1
  path: ^1.8.0
  protobuf: ^3.1.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^5.0.0
  protoc_plugin: ^21.1.2
  test: ^1.17.5
