name: jot
description: An experimental documentation generator for Dart projects.
version: 0.1.0-dev
repository: https://github.com/dart-lang/labs/tree/main/pkgs/jot
issue_tracker: https://github.com/dart-lang/labs/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Ajot

publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  # bin/
  cli_util: ^0.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

   # lib/
  analyzer: ^6.4.0
  args: ^2.4.0
  collection: ^1.17.0
  dart_style: ^2.3.6
  js: ^0.6.0
  markdown: ^7.0.0
  meta: ^1.11.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  crypto: ^3.0.0
  dart_flutter_team_lints: ^3.0.0
  http: ^1.1.0
  test: ^1.23.0

# Test packages.
workspace:
  - test/fixtures/demo
  - test/fixtures/server
