include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  errors:
    todo: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - avoid_catches_without_on_clauses
    - avoid_dynamic_calls
    - avoid_positional_boolean_parameters
    - avoid_unused_constructor_parameters
    - directives_ordering
    - lines_longer_than_80_chars
    - prefer_asserts_in_initializer_lists
    - prefer_if_elements_to_conditional_expressions
    - unawaited_futures
    - unnecessary_library_directive
    - unnecessary_parenthesis
    - unreachable_from_main
    - prefer_final_locals
