name: unix_api
description:  Access to POSIX APIs.
version: 0.1.0-wip
repository: https://github.com/dart-lang/labs/tree/main/pkgs/unix_api
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  code_assets: ^0.19.0
  ffi: ^2.1.4
  hooks: ^0.19.5
  logging: ^1.3.0
  native_toolchain_c: ^0.16.0

dev_dependencies:
  dart_flutter_team_lints: ^3.4.0
  ffigen: ^19.1.0
  tests:
    path: tests

