name: Health
permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@5554bbb7cb382aed6943ce918c859aa17df098e1
    with:
      ignore_coverage: "**.mock.dart,**.g.dart"
      ignore_license: "**.mock.dart,**.g.dart,**.mocks.dart"
    permissions:
      pull-requests: write
