name: Health
permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@467f1e9b190d72f75b906112979fa21483ac43b9
    with:
      ignore_coverage: "**.mock.dart,**.g.dart"
      ignore_license: "**.mock.dart,**.g.dart,**.mocks.dart"
    permissions:
      pull-requests: write
