name: Health
permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@565fdb767afb9f53706ace2a78bdbd0d491b1fa0
    with:
      ignore_coverage: "**.mock.dart,**.g.dart"
      ignore_license: "**.mock.dart,**.g.dart,**.mocks.dart"
    permissions:
      pull-requests: write
