name: package:native_synchronization
permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/native_synchronization.yml'
      - 'pkgs/native_synchronization/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/native_synchronization.yml'
      - 'pkgs/native_synchronization/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  analyze:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: pkgs/native_synchronization
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [dev, stable]

    steps:
      # These are the latest versions of the github actions; dependabot will
      # send PRs to keep these up-to-date.
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

  test:
    needs: analyze
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: pkgs/native_synchronization
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [dev, stable]
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - uses: dart-lang/setup-dart@0a8a0fc875eb934c15d08629302413c671d3f672
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
