# A CI configuration to post comments to PRs.
#
# This workflow will have permissions to create comments on the PR even if the
# original workflow couldn't.

name: Comment on the pull request
permissions:
  contents: read

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: 
      - Health
    types:
      - completed

jobs:
  upload:
    uses: dart-lang/ecosystem/.github/workflows/post_summaries.yaml@b754137f9fc45e4adf65e1af5100276b9fb5ddb5
    permissions:
      pull-requests: write
